name: Feature request / 功能请求
description: Request a new feature / 请求一个新功能
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    id: problem
    attributes:
      label: 是否因为遇到问题而提出新功能? / Is your feature request related to a problem?
      description: 清晰，简洁地描述此问题 / A clear and concise description of what the problem is.
    validations:
      required: false
  - type: textarea
    id: solution
    attributes:
      label: 描述你想要的解决方案 / Describe the solution you'd like
      description: 清楚并简洁地描述你希望发生什么 / A clear and concise description of what you want to happen.
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: 更多内容 / Additional context
      description: 关于此功能请求的更多信息 (或截图, 日志) / Any other context, screenshots or logs about the feature request here.
    validations:
      required: false
  - type: checkboxes
    id: confirm
    attributes:
      label: 提交前请确认 / Please confirm before submitting
      options:
        - label: 我确认现有的 Issues 列表中没有与这个重复的问题 / I confirm there is no duplicate.
          required: true
        - label: 我确认已经删除日志中的敏感信息 (如 secret) / I confirm there is no secret in logs.
          required: true
        - label: 我确认检查了上面的事项，并创建此 Issue / I confirm to commit this issue.
          required: true
        - label: 我未认真查看上面所有内容，只是一味勾选所有复选框 / Don't check me.
          required: false
