<script setup lang="ts">
import { onMounted, ref } from 'vue'; import Notice from '@/components/Notice.vue'; import { useDashboardStore } from '@/stores/dashboard'
const store = useDashboardStore(); const name = ref(''); const issued = ref(''); const notice = ref(''); const error = ref(''); const busy = ref(false)
async function create() { if (!name.value.trim()) return; busy.value = true; error.value = ''; try { issued.value = await store.createToken(name.value.trim()); name.value = ''; notice.value = '令牌已签发，请立即保存。' } catch (reason) { error.value = reason instanceof Error ? reason.message : '签发失败' } finally { busy.value = false } }
async function revoke(token: string) { busy.value = true; try { await store.revokeToken(token); notice.value = '令牌已吊销' } catch (reason) { error.value = reason instanceof Error ? reason.message : '吊销失败' } finally { busy.value = false } }
async function copy(value: string) { await navigator.clipboard.writeText(value); notice.value = '已复制到剪贴板' }
onMounted(async () => { store.tokens = await (await import('@/services/api')).api.request('/api/v1/tokens') })
</script>
<template><div class="page"><div class="page-heading"><div><span class="eyebrow">设备鉴权</span><h1>设备令牌</h1></div></div><Notice :message="notice" type="success"/><Notice :message="error" type="error"/><section class="section"><h2>签发新令牌</h2><form class="inline-form" @submit.prevent="create"><input v-model="name" placeholder="例如：办公室电脑" required/><button class="primary" :disabled="busy">签发</button></form><div v-if="issued" class="secret-box"><p>此令牌仅在这里完整展示一次：</p><code>{{ issued }}</code><button @click="copy(issued)">复制</button><button class="ghost" @click="issued = ''">已保存</button></div></section><section class="section"><div class="section-title"><h2>现有令牌</h2><span>{{ store.tokens.length }} 个</span></div><p v-if="!store.tokens.length" class="empty">尚未签发设备令牌。</p><div v-else class="list"><article v-for="token in store.tokens" :key="token.token"><div><strong>{{ token.name || '未命名令牌' }}</strong><p>创建于 {{ new Date(token.created * 1000).toLocaleString() }} · {{ token.expire ? `到期 ${new Date(token.expire * 1000).toLocaleDateString()}` : '永不过期' }}</p></div><button class="danger ghost" :disabled="busy" @click="revoke(token.token)">吊销</button></article></div></section></div></template>
